.TH CATERM 1 "2025-06-06" "1.2" "General Commands Manual"
.SH NAME
caterm \- the one-liner terminal

.SH SYNOPSIS
.B caterm

.SH DESCRIPTION
caterm is a minimalist, ephemeral shell alias that lets you write and run temporary
shell scripts using a heredoc. The alias looks like a kaomoji >_<.

You write your script, end with the word "run", and it executes the code in a
temporary file which is then deleted.

.SH USAGE
Example:

.nf
$ caterm
echo "hello world"
run
hello world
.fi

.SH INSTALLATION
Add the following line to your shell config (e.g. ~/.zshrc):

.nf
source /usr/share/caterm/caterm.sh
.fi

Or add one of the following aliases directly, replacing with your preferred shell:

.nf
alias caterm='>_<<run; sh _; rm _'       # uses sh
alias caterm='>_<<run; zsh _; rm _'      # uses zsh
alias caterm='>_<<run; bash _; rm _'     # uses bash
alias caterm='>_<<run; python3 _; rm _'  # uses python3
.fi

Each alias script is installed to /usr/share/caterm/ with a file extension indicating the interpreter.

.SH FILES
/usr/share/caterm/caterm.sh       (sh alias)
/usr/share/caterm/caterm.zsh      (zsh alias)
/usr/share/caterm/caterm.bash     (bash alias)
/usr/share/caterm/caterm.py3.sh   (python3 alias)
/usr/share/caterm/LICENSE         (license text)
/usr/share/man/man1/caterm.1      (man page)

To uninstall, remove these files and remove any references in your shell rc files.

.SH LICENSE
This software is released under The Unlicense. See /usr/share/caterm/LICENSE
for details or visit <https://unlicense.org>

.SH AUTHOR
Inspired by cursed shell energy. Made by theoddcell (https://oddcell.ca/)

.SH BUGS
If the file "_" already exists, it will be overwritten without warning.
Not intended for permanent scripts.

.SH SEE ALSO
sh(1), zsh(1), bash(1), cat(1)
